include:
  - docker-compose.superset.yaml
  - docker-compose.analytics.yml

services:
  database:
    image: georchestra/database:latest
  ldap:
    image: georchestra/ldap:latest
    ulimits:
      nofile:
        soft: "1024"
        hard: "1024"

  gateway:
    image: georchestra/gateway:latest-debug
    environment:
      JAVA_TOOL_OPTIONS: >
        -javaagent:/etc/georchestra/gateway/libs/opentelemetry-javaagent.jar
        -Dotel.javaagent.enabled=true
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.exporter.otlp.endpoint=http://vector:4317
        -Dotel.instrumentation.logback-appender.experimental.capture-mdc-attributes=*
        -Dotel.traces.exporter=none
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=otlp
    ports:
      - 8080:8080
    volumes:
      - ./datadir:/etc/georchestra

  geoserver:
    image: georchestra/geoserver:latest
    environment:
    - GEOSERVER_CSRF_DISABLED=true
    - JAVA_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
    volumes:
      - ./datadir:/etc/georchestra
    ports:
      - "5005:5005"
