# File included by gateway.yaml to set up the security/authentication aspects
# of the application.

georchestra:
  gateway:
    security:
      createNonExistingUsersInLDAP: false
      events:
        rabbitmq:
          # Note usually enableRabbitmqEvents, rabbitmqHost, etc. come from georchestra's default.properties
          enabled: false
      oauth2:
        enabled: false
        proxy:
          enabled: false
      ldap:
        default:
          enabled: true
