services:

  database:
    image: georchestra/database:latest

  ldap:
    image: georchestra/ldap:latest
    ulimits:
      nofile:
        soft: "1024"
        hard: "1024"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21

  console:
    image: georchestra/console:latest
    volumes:
      - ./datadir:/etc/georchestra

  geonetwork:
    image: georchestra/geonetwork:24.0.0-dev
    environment:
    - PGHOST=database
    - PGPORT=5432
    - PGDATABASE=georchestra
    - PGUSER=georchestra
    - PGPASSWORD=georchestra
    - CONSOLE_HOST=console
    - ES_HOST=elasticsearch
    - ES_PORT=9200
    - JAVA_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
    depends_on:
    - console
    - database
    - elasticsearch
    ports:
    - 8080:8080
    - 5005:5005
