services:
  database:
    image: georchestra/database:latest
  ldap:
    image: georchestra/ldap:latest
    ulimits:
      nofile:
        soft: "1024"
        hard: "1024"
  cas:
    image: georchestra/cas:latest
    volumes:
      - ./datadir:/etc/georchestra
  elasticsearch:
    # sudo sysctl -w vm.max_map_count=262144
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  console:
    image: georchestra/console:latest
    volumes:
      - ./datadir:/etc/georchestra
  geonetwork:
    image: georchestra/geonetwork:latest
    volumes:
      - ./datadir:/etc/georchestra
    environment:
    - PGHOST=database
    - PGPORT=5432
    - PGDATABASE=georchestra
    - PGUSER=georchestra
    - PGPASSWORD=georchestra
    - CONSOLE_HOST=console
    - ES_HOST=elasticsearch
    - ES_PORT=9200
    - CUSTOM_SCRIPTS_DIRECTORY=/etc/georchestra/geonetwork/scripts
    depends_on:
      database:
        condition: service_healthy
      console:
        condition: service_started
      elasticsearch:
        condition: service_started
  geoserver:
    image: georchestra/geoserver:latest
  import:
    image: georchestra/datafeeder-frontend:latest
  datafeeder:
    image: georchestra/datafeeder:latest
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./datadir:/etc/georchestra
    ports:
      - "5005:5005"
    environment:
      - JAVA_OPTIONS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005
  smtp:
    image: camptocamp/smtp-sink:latest
  proxy:
    image: georchestra/security-proxy:latest
    ports:
    - 8080:8080
    volumes:
    - ./datadir:/etc/georchestra
