services:
  ldap:
    image: georchestra/ldap:latest
    restart: always
    ports:
      - 3891:389
    ulimits:
          nofile:
            soft: "1024"
            hard: "1024"

  gateway:
    image: georchestra/gateway:latest
    depends_on:
      - ldap
    volumes:
      - ./datadir:/etc/georchestra
    environment:
      - JAVA_TOOL_OPTIONS=-Dgeorchestra.datadir=/etc/georchestra -Dspring.profiles.active=docker -Xmx512M -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
    restart: always
    ports:
      - 8080:8080
      - 5005:5005

  flask:
    build:
      context: header-reader
      target: builder
    ports:
      - '8000:8000'