competenceAreaEnabled=true
orgTypeValues=Association,Company,NGO,Individual,Other
AreaMapCenter=3.06, 50.63
AreaMapZoom=11
AreasUrl=cities.geojson
AreasKey=NOM_COM
AreasValue=nom
AreasGroup=code_insee
